# Generated by Django 4.0.2 on 2022-02-26 21:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=50, unique=True, verbose_name='user_id')),
                ('user_name', models.CharField(max_length=100, verbose_name='user name')),
                ('user_lastname', models.CharField(max_length=100, verbose_name='user lastname')),
                ('user_email', models.EmailField(max_length=100, verbose_name='user email')),
                ('user_job', models.CharField(max_length=50, verbose_name='user job')),
                ('user_date_join', models.DateTimeField(auto_now_add=True, verbose_name='user time join')),
                ('user_last_login', models.DateTimeField(auto_now=True, verbose_name='user last login')),
                ('user_profile', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.TextField(max_length=200)),
                ('price', models.FloatField(default=0.0)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('contactFb', models.TextField(max_length=100, null=True)),
                ('contactTw', models.TextField(max_length=100, null=True)),
                ('contactEmail', models.TextField(max_length=100, null=True)),
                ('contactOther', models.TextField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
